### ISSUE TITLE
Improve figma prototype

### ISSUE THREAD

**Issue by lucas-giraldelli** [lucas-giraldelli/cerv-infancia#4]
Change "Ficha de Matricula" to match database tables
[Figma project](https://www.figma.com/file/eiOlVJ9t8PYIPXBFU1CoQx/Painel-administrativo?node-id=0%3A1&mode=dev)

**Comment by willtrev** [comment]
[Figma project](https://www.figma.com/file/eiOlVJ9t8PYIPXBFU1CoQx/Painel-administrativo?node-id=0%3A1&mode=dev)
